name: Notify Slack When Issue Closes

on:
  issues:
    types: [closed]

jobs:
  notify:
    if: startsWith(github.event.issue.title, 'AEMY Catalyze -')
    runs-on: ubuntu-latest
    steps:
      - name: Get Slack thread_ts from issue comments
        id: get_thread_ts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const threadComment = comments.data.reverse().find(c => c.body.startsWith('Slack thread_ts: '));
            if (threadComment) {
              const thread_ts = threadComment.body.replace('Slack thread_ts: ', '').trim();
              core.setOutput('thread_ts', thread_ts);
            }
      - name: Notify Slack that E2E test completed
        uses: slackapi/slack-github-action@v1.25.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "*E2E Crosswalk Test Completed* ✅\nIssue closed: <${{ github.event.issue.html_url }}|${{ github.event.issue.title }}>",
              "thread_ts": "${{ steps.get_thread_ts.outputs.thread_ts }}"
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 